### ISSUE TITLE
刚安装好 1.12.3 版本的 controller-manager 的运行状态好像不健康

### ISSUE THREAD

**Issue by xiangxiaoc** [xiaojiaqi/k8seasy_release_page#1]
具体情况是在单节点上，Ubuntu 18.04.1，执行了`./installer --install`，然后就检查了各组件的情况，返回如下：
```sh
root@ubuntu:~# kubectl get componentstatuses 
NAME                 STATUS      MESSAGE                                                                                                                                  ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"   
scheduler            Healthy     ok                                                                                                                                       
etcd-0               Healthy     {"health":"true"} 
```
对应下载到的包文件如下：
```sh
root@ubuntu:~# ls
dashboard.kubeconfig  installer  pack.1.12.3.001.bin
```
好像是没有使用https去访问，不知道对正常使用有没有影响

**Comment by xiaojiaqi** [comment]
应该是正常的，因为http接口被关闭了。

可以用下面命令检查一下

sudo systemctl status kube-apiserver  | grep  Active 
sudo systemctl status  kube-controller-manager  | grep  Active 
sudo systemctl status  kube-proxy  | grep  Active 
sudo systemctl status  kube-scheduler  | grep  Active 
sudo systemctl status  kubelet  | grep  Active 
sudo systemctl status  flanneld  | grep  Active 
sudo systemctl status  haproxy  | grep  Active 
sudo systemctl status  docker  | grep  Active 
sudo systemctl status  etcd | grep  Active 

其次检查/var/log/k8s/里的日志， 如果有大量日志文件诞生，说明的确有bug. 你可以看看 dashboard 里的状态是否正常，启动一个简单的业务是否正常，来加以判断系统是否正常。
