### ISSUE TITLE
主机ip不在192.168.0.1/255 - 192.168.10.0/255范围内可以使用吗？

### ISSUE THREAD

**Issue by zoux86** [xiaojiaqi/k8seasy_release_page#2]
192.168.14.78  worker	
192.168.14.68	worker	
192.168.14.75	worker	
192.168.14.81  master
我有上面四台主机，按照教程部署时候出现这个问题。
![image](https://user-images.githubusercontent.com/14087435/50217493-c7606480-03c3-11e9-80c3-4d6b07078c13.png)

这个有办法解决吗？

**Comment by xiaojiaqi** [comment]
不可以，因为系统里面需要证书，目前证书是在文件内部的，所以没办法生成。你可以用这个办法 绕过去为每个主机多设置一个ip  比如 192.168.14.78  你就这样  假设没有ip冲突。你的设备号是eth1
sudo ip addr add 192.168.1.78/24 dev eth1

**Comment by xiaojiaqi** [comment]
新版本支持 192.168.xx 172.16.xx-172.32.xx 10.0.xx 10.29.xx
这些网段

**Comment by xiaojiaqi** [comment]
004 版本 已经支持以上网段

**Comment by zoux86** [comment]
@xiaojiaqi thanks
