### ISSUE TITLE
为什么不采用脚本，而采用go去写呢，不累吗

### ISSUE THREAD

**Issue by wanghaiqing2015** [xiaojiaqi/k8seasy_release_page#4]
RT

**Comment by xiaojiaqi** [comment]
good question,  这个问题可以从很多方面来看，适用性，简单性。利用脚本 大部分指python shell 或者ansible 在很多时候有很多便利，但是有一个最大的问题，环境依赖。这些依赖表现在 python 版本 机器本身安装的python2 还是python3，使用的第三方类库 版本是什么？安装各种python 库 版本的不同可能造成不同的结果。shell 上又有bash cshell, 这些解释器执行上又有不同。  最终结果 就是 在各种平台上可能无法保持一致。 用户安装会失败！

为解决最小白用户的使用感受，不去安装任何类库，不考虑使用的操作系统 我使用GO 可以解决这个问题。
