### ISSUE TITLE
next plan devlopment calico

### ISSUE THREAD

**Issue by lilinji** [xiaojiaqi/k8seasy_release_page#5]

**Comment by lilinji** [comment]
HI 下一步有计划 开发一版 支持 calico 的么？

**Comment by xiaojiaqi** [comment]
感谢支持， 很抱歉 不太注意看issue.

计划 基本如下： 
 
0 支持自建证书 支持所有网段 (完成)
1 不再支持keepalive,   而使用ha nginx方式的高可用 (完成)
2 支持云环境 本地环境 (正在做)
3 支持calico
4 支持内置service mesh

因为 最近几个版本 时间很少，测试不够，所以质量不好。准备重新重构一下后放出。

**Comment by lilinji** [comment]
嗯嗯， 好的，重构之后我可以作为🐰使用提出建议

**Comment by xiaojiaqi** [comment]
可以来 QQ 群 778526002, 下载最新版本吃螃蟹，calico 功能已添加
