### ISSUE TITLE
希望适配centos 8

### ISSUE THREAD

**Issue by mzkingk** [xiaojiaqi/k8seasy_release_page#7]
centos7确实可用，但是8上，upgrade system那里有如下错误，因为centos8下默认是不包含nfs、ntp的

> 错误：没有任何匹配: nfs ntp

**Comment by xiaojiaqi** [comment]
got it,  看来我得先去找个centos 8 先。

**Comment by xiaojiaqi** [comment]
http://dl.k8seasy.com/installer-centos8

重新做了一个新版本 支持chrony，烦劳 在centos8 下测试一下。

**Comment by xiaopohou** [comment]
写真的真好，希望加一个微信，我要发一个红包！必须赞助
