### ISSUE TITLE
sudo ./installer --genkey -hostlist=192.168.2.50 报错

### ISSUE THREAD

**Issue by OnlyChange** [xiaojiaqi/k8seasy_release_page#8]
Error on cmd:  sudo gpasswd -a k8s wheel  err:  exit status 3  file:  /home/aaa/kubs/common/system_init/system_adduser.go   40  data:  gpasswd: group 'wheel' does not exist in /etc/group

**Comment by xiaojiaqi** [comment]
目前只支持 centos 系列， 建议你使用centos, 或者等待下半年支持ubuntu 系统

**Comment by xiaojiaqi** [comment]
fixed， dl.k8seasy.com  下载最新版本，已经支持ubuntu
